name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Make Gradlew Executable
        run: |
            chmod +x ./gradlew

      - name: Build and Test with Gradle
        run: |
            ./gradlew clean build test
          
  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SUPER_SECRET }}

      - name: Build image
        run: docker build -t ghcr.io/lingwangcode/tdd-uppgift_grupp11/test-docker-with-githubactions .
      - name: Push image
        run: docker push ghcr.io/lingwangcode/tdd-uppgift_grupp11/test-docker-with-githubactions:latest

  fake-deployment:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Fake Deployment
        run: echo "ghcr.io/lingwangcode/tdd-uppgift_grupp11/test-docker-with-githubactions"
